const get_participant_map = () => {
    const data = [
        { name: 'Rohitt Vashishtha', batch: 2015 },
        { name: 'Karthik Nagaraj', batch: 2016 },
        { name: 'Ramana Sriram', batch: 2018 },
        { name: 'Monith Sourya', batch: 2016 },
        { name: 'Ananya Mohapatra', batch: 2018 },
        { name: 'Shanmukh Nama', batch: 2016 },
        { name: 'Musaiyab Ali Mirza', batch: 2016 },
        { name: 'Kushagra K Chanda', batch: 2015 },
        { name: 'Viswanatha Kasyap Pasumarthy', batch: 2015 },
        { name: 'Sandeep Jimmy', batch: 2017 },
        { name: 'Vedika Kulkarni', batch: 2017 },
        { name: 'Manish Kumar', batch: 2017 },
        { name: 'Vamsi Nallapareddy', batch: 2017 },
        { name: 'Chellapilla Shri Akhil', batch: 2015 },
        { name: 'Rushabh Musthyala', batch: 2018 },
        { name: 'Vinith Bhandari', batch: 2016 },
        { name: 'Tushar Aggarwal', batch: 2017 },
        { name: 'Paavani Khanna', batch: 2018 },
        { name: 'Shreejee Agarwal', batch: 2018 },
        { name: 'Nivedan Vishwanath', batch: 2018 },
        { name: 'Prajjwal Vijaywargiya', batch: 2017 },
        { name: 'Aditya Ramaswami', batch: 2016 },
        { name: 'Triyasha Ghosh Dastidar', batch: 2017 },
        { name: 'Suhita Saha', batch: 2015 },
        { name: 'Venkatesh Jaya', batch: 2017 },
        { name: 'Palak Oswal', batch: 2015 },
        { name: 'Nikita Mandapati', batch: 2015 },
        { name: 'Shanmukh Kali Prasad', batch: 2017 },
        { name: 'Meghna Chintalpudi', batch: 2018 },
        { name: 'Swetha Mamidipoodi', batch: 2018 },
        { name: 'Harsha Sinha', batch: 2017 },
        { name: 'Tushar Kanth', batch: 2015 },
        { name: 'Archana Swaminathan', batch: 2016 },
        { name: 'Kaushik Sathishkumar', batch: 2018 },
        { name: 'Tarun Agrawal', batch: 2018 },
        { name: 'Asha Cherukuri', batch: 2017 },
        { name: 'Sriya Suri', batch: 2017 },
        { name: 'Aishwarya Rebelly', batch: 2016 },
        { name: 'Raghavendra Challawar', batch: 2017 },
        { name: 'Sanath Salil', batch: 2018 },
        { name: 'Anudeep Reddy', batch: 2018 },
        { name: 'Tejas Vaid', batch: 2017 },
        { name: 'Adarsh Mishra', batch: 2018 },
        { name: 'Chatrik Singh Mangat', batch: 2017 },
        { name: 'Mohammed Burk', batch: 2017 },
        { name: 'Akshay Tiwari', batch: 2018 },
        { name: 'Harsha Sista', batch: 2016 },
        { name: 'Abhinav Krishnan', batch: 2018 },
        { name: 'Niharika Shankar', batch: 2017 },
        { name: 'Vamsi BG', batch: 2017 },
        { name: 'Mrunalini Ramnath', batch: 2017 },
        { name: 'Rohit Dwivedula', batch: 2017 },
        { name: 'Aditya Gayatri Sastry Kaipa', batch: 2017 },
        { name: 'Siddharth Sampath', batch: 2017 },
        { name: 'Shashank Sistla', batch: 2017 },
        { name: 'Abhimanyu Dasgupta', batch: 2017 },
        { name: 'Poornima Venkatapuram', batch: 2017 },
        { name: 'Shreyam Kumar', batch: 2017 },
        { name: 'Jaya Pavan Yalamati', batch: 2018 },
        { name: 'Eishita Tripathi', batch: 2018 },
        { name: 'Shuddhabho Nandi', batch: 2018 },
        { name: 'Adithya Warrier', batch: 2018 },
        { name: 'Yogitha Garlapati', batch: 2018 },
        { name: 'Maithree Venkatesan', batch: 2018 },
        { name: 'Saandra Nandakumar', batch: 2018 },
        { name: 'Venkata Tharun Gangula', batch: 2018 },
        { name: 'Ishita Gupta', batch: 2018 },
        { name: 'Sharique Creates', batch: 2018 },
        { name: 'Akshitha Reddy', batch: 2018 } ];
    return data;
};

module.exports = get_participant_map();
